packages:
  - packages/*

catalog:
  "@biomejs/biome": 2.0.5
  "@changesets/cli": 2.29.5
  "@playwright/test": 1.53.1
  "@types/node": 22.15.30
  "@vitest/coverage-istanbul": 3.2.4
  "@vitest/expect": 3.2.4
  "serve": 14.2.4
  "tsup": 8.5.0
  "typescript": 5.8.3
  "vitest": 3.2.4
  "yaml": 2.8.0

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
